apiVersion: v1
kind: Pod
metadata:
  name: args
spec:
  containers:
    - name: args
      image: busybox
      command: ['/bin/sh', '-c', 'echo FirstName: $(FIRSTNAME) and LastName: $(LASTNAME)']
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: multimap
              key: given
        - name: LASTNAME
          valueFrom:
            configMapKeyRef:
              name: multimap
              key: family