apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuard
spec:
  selector:
    matchLabels:
      run: kuard
  replicas: 3
  template:
    metadata: 
      labels: 
        run: kuard
      annotations:
        kubernetes.io/change-cause: "Update to blue kuard"
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue