apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 3
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          command: [ sh, -c, source /redis-config/init.sh ]
          image: redis:4.0.11-alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /redis-config
              name: config
            - mountPath: /redis-data
              name: data
        - name: sentinel
          command: [ sh, -c, source /redis-config-src/sentinel.sh ]
          image: redis:4.0.11-alpine 
          volumeMounts:
            - mountPath: /redis-config-src
              name: config
            - mountPath: /redis-config
              name: data
      volumes:
        - name: config
          configMap: 
            defaultMode: 420
            name: redis-config 
        - name: data
          emptyDir:
            